# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # Gesdinet\JWTRefreshTokenBundle\Service\RefreshToken: '@gesdinet.jwtrefreshtoken'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    App\EventListener\ExceptionListener:
        arguments:
            - '@logger'
            - '@translator'
            - '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: sendErrors, priority: 0 }
            - { name: kernel.event_listener, event: kernel.exception, method: logErrors, priority: 10 }

    App\ValueResolver\DtoResolver:
        arguments:
            - '@serializer'
            - '@validator'
        tags:
            - { name: controller.argument_value_resolver, priority: 150 }

    fixture_loader:
        class: App\Fixture\FixtureLoader
        arguments:
            - '%kernel.project_dir%'

    App\Command\FixtureLoadCommand:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@fixture_loader'
        tags: [ { name: console.command, command: fixture:load } ]

    App\Search\SearchService:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@event_dispatcher'